package qmtv.email;

public class EmailConfig{
	/**如需发送邮件，请配置SMTP host，比如163邮箱：smtp.163.com**/
	public static String smtpHost;
    /**发送邮箱的账号**/
	public static String sender;
	/**发送邮箱的账号密码**/
	public static String sendPassword;
	/**邮件接收者账号**/
	public static String receivers;
	/**邮件抄送者账号**/
	public static String chaosong;
    /**邮件主题，默认："Test Report Generated By Log4Reports"**/
	public static String subject;
	
	
	public EmailConfig(Builder builder) {
		EmailConfig.smtpHost = builder.smtpHost;
		EmailConfig.sender = builder.sender;
		EmailConfig.sendPassword = builder.sendPassword;
		EmailConfig.receivers = builder.receivers;
		EmailConfig.chaosong = builder.chaosong;
		EmailConfig.subject = builder.subject;
	}

	public static class Builder {
		private String smtpHost;
		private String sender;
		private String sendPassword;
		
		private String receivers;
		private String chaosong;
		private String subject = "Test Report Generated By qmtv_API_Auto_Test";

		public Builder setSmtpHost(String smtpHost) {
			this.smtpHost = smtpHost;
			return this;
		}
		
		public Builder setSender(String sender) {
			this.sender = sender;
			return this;
		}
		

		public Builder setSendPassword(String sendPassword) {
			this.sendPassword = sendPassword;
			return this;
		}
		
		public Builder setReceivers(String receivers) {
			this.receivers = receivers;
			return this;
		}
		
		public Builder setChaosong(String chaosong) {
			this.chaosong = chaosong;
			return this;
		}
		
		public Builder setSubject(String subject) {
			this.subject = subject;
			return this;
		}
		
        public EmailConfig build(){
        	return new EmailConfig(this);
        }
	}
}
